In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

Creating array

In [3]:
a=np.array(l)  #to convert into array

In [4]:
a

array([1, 2, 3, 4])

In [5]:
ar=np.asarray(l)

In [6]:
ar

array([1, 2, 3, 4])

In [7]:
arr=np.asanyarray(l)

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(a)    #ndarray=n-dimensional array

numpy.ndarray

numpy can store multi-dimensional data

In [10]:
s=np.array([[1,2],[3,4]])  #two-dimensional

In [132]:
s.ndim

2

In [133]:
s

array([[1, 2],
       [3, 4]])

Creating matrix

In [11]:
b=np.matrix(l)  #matrix is by default 2-dimensional

in matrix, row is represented on x-axis,whereas column is reprented on y-axis

In [12]:
b   #matrix is subset of array

matrix([[1, 2, 3, 4]])

Converting matrix to array

In [13]:
np.asanyarray(b)   #asanyarray does not convert matrix into array

matrix([[1, 2, 3, 4]])

In [14]:
np.asarray(b)   #asarray converts matrix into array

array([[1, 2, 3, 4]])

In [15]:
np.array(b)  #array also converts matrix into array

array([[1, 2, 3, 4]])

Assigning the value of an array to another variable

In [16]:
a=np.array(l)

In [17]:
c=a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
c[0]

1

In [21]:
c[0]=100   #changing value of 'c' at index zero.

In [22]:
c

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

we have changed the value at zero index in array 'c', but the value of array 'a' is also changed because when we assigned c=a,at that time new object was not created ....instead the same 'a' values were pointed towards 'c'.Memory location was not changed.This concept is called swallow copy.

Copying an array

In [24]:
d=np.copy(a)   #creating copy of array 

In [25]:
d

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
a[1]=455

In [28]:
a

array([100, 455,   3,   4])

In [29]:
d

array([100,   2,   3,   4])

when we create a copy of an array using copy() function....a new copy of array is created at a different location....hence...any changes made at 'a' is not impacted at 'd'. This is called deep copy.

Various functions to generate different types and dimensions of array

In [30]:
np.fromfunction(lambda i,j:i==j,(3,3))  #helps in generating arrays

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

here,3*3 matrix is created...then codition is checked ...i is row index and j is column index.If i==j,then it returns true else false. ( 0th row and 0th column so true,0th row and 1st column so false...and so on.)

In [31]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

here,3*3 matrix is created ,then,row index and column index are multiplied

In [32]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [33]:
iterable=(i*i for i in range(5))

In [34]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [36]:
np.fromstring('234,678 ,234',sep=' ,')

array([234., 678., 234.])

In [37]:
l1=[2,3,4,5,6]

In [38]:
ar1=np.array(l1)

In [39]:
ar1

array([2, 3, 4, 5, 6])

In [40]:
#to know dimension of array ,ndim is used
ar1.ndim

1

In [41]:
l2=[[12,56,45],[67,36,33]]
ar2=np.array(l2)

In [42]:
ar2

array([[12, 56, 45],
       [67, 36, 33]])

In [43]:
ar2.ndim

2

In [44]:
#to know size of array..that is no. of elements in array
ar2.size

6

In [45]:
ar1.size

5

In [46]:
#to know shape of array...that is ...no. of rows and columns
ar1.shape

(5,)

In [47]:
ar2

array([[12, 56, 45],
       [67, 36, 33]])

In [48]:
ar2.shape   #2 rows and 3 columns are there

(2, 3)

In [49]:
ar1.dtype   #tells datatype of array

dtype('int32')

In [50]:
ar2.dtype

dtype('int32')

In [51]:
new_ar=np.array([(1.4,45,45),(23,25,66)])

In [52]:
new_ar

array([[ 1.4, 45. , 45. ],
       [23. , 25. , 66. ]])

In [53]:
new_ar.dtype

dtype('float64')

In [54]:
range(2,8)  #range function always takes integer

range(2, 8)

In [55]:
list(range(2,8))

[2, 3, 4, 5, 6, 7]

to take floating point as starting and end points,we have arange in numpy.It can generate a range of numbers that can either be integer or float

In [56]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [57]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [58]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [59]:
np.linspace(1,5,10)   #it divides numbers between 1 and 5(or any given number ) into 10 or other specified divisions

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [60]:
np.zeros(5)  #will generate zeroes (single dimension)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((5,6))  #5 rows six column (2 dimensional)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [62]:
np.zeros((4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
z=np.zeros((4,4,2)) #4 rows 2 columns are there and total no. of arrays are 4

In [64]:
z.ndim

3

in multi-dimensional,one array is reprented behind another array...in graph....maximum 3 dimensional can be reprented as graph or visualized.

In [65]:
np.ones((4,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [66]:
np.ones(2)

array([1., 1.])

In [67]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
o=np.ones((3,3))

In [69]:
o.ndim

2

In [70]:
o+2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [71]:
o*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [72]:
m=o+2

In [73]:
m*6

array([[18., 18., 18.],
       [18., 18., 18.],
       [18., 18., 18.]])

create an empty array

In [74]:
np.empty((3,6))


array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [75]:
#identity matrix   that is.....no. of rows is equal to no. of columns
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.linspace(2,4,21)   

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ])

In [77]:
np.logspace(2,5,9) #same as linespace except it gives log of that number

array([   100.        ,    237.13737057,    562.34132519,   1333.52143216,
         3162.27766017,   7498.94209332,  17782.79410039,  42169.65034286,
       100000.        ])

In [78]:
np.logspace(2,5,9, base=2)   #by default base is 10

array([ 4.        ,  5.18735822,  6.72717132,  8.72406186, 11.3137085 ,
       14.67206469, 19.02731384, 24.67537321, 32.        ])

In [79]:
np.random.randn(3,4)   #produces random array of specified size

array([[ 0.33547288, -0.25467169,  0.89740851,  0.88618104],
       [-1.01900264,  0.68076511, -0.59276716,  0.46984029],
       [-0.32506555,  0.46240472, -2.01140437,  0.56951329]])

In [80]:
import pandas as pd

In [81]:
d=np.random.randn(3,4)   #will always generate data whose mean is zero and standard deviation is 1

In [82]:
pd.DataFrame(d)   #create dataframe

0         1         2         3
0 -1.430653  0.289609 -0.145518 -0.297988
1  0.254474  0.658378 -0.738520  1.639429
2  0.060100 -0.681202  1.223205 -0.009368

In [83]:
np.random.rand(3,5)  #generates any data

array([[0.26543337, 0.25077959, 0.18019685, 0.20076699, 0.32568724],
       [0.2806365 , 0.74722623, 0.6362209 , 0.57599094, 0.85688496],
       [0.84456393, 0.94253908, 0.67373283, 0.96765675, 0.75421797]])

In [84]:
np.random.randint(1,99,(3,4))  #will generate integer within specified range or limit

array([[63, 73, 25, 72],
       [12, 61, 61, 92],
       [41, 67, 32, 19]])

In [85]:
d1=np.random.randint(1,111,(8,9)) 

In [86]:
pd.DataFrame(d1)

0   1    2   3    4   5   6    7   8
0   80  99   20  92   91  94  28   12   7
1  108  96   11  80   64  99  22  106   8
2   21  34   36  44  101   3  40   93  31
3   66  37   51  73   93  59  64   47   1
4   81  63  105  31   60  97  85   66  10
5   20  25   65  40   44  56  35    4  83
6   50  19   95  17   79  33  32   57  47
7    3  10   94  40   55  56   1   52  39

In [87]:
m=np.random.rand(3,4) 

In [88]:
m.reshape(6,2)   #it will reshape the same data of into specified size

array([[0.11765187, 0.74640037],
       [0.56633394, 0.55493823],
       [0.12560793, 0.06964189],
       [0.04378926, 0.03475215],
       [0.15789712, 0.57764405],
       [0.14047119, 0.05184872]])

In [89]:
m.reshape(1,12)

array([[0.11765187, 0.74640037, 0.56633394, 0.55493823, 0.12560793,
        0.06964189, 0.04378926, 0.03475215, 0.15789712, 0.57764405,
        0.14047119, 0.05184872]])

in reshape,the new size has to be multiple of orginal size   ... that is if orginal size is 4*3.....then new size will be such that its product is also 12.....this means it can be 6*2,3*4,2*6,1*12 etc. Even if we don't specify column or give any negative number as column....it will still take a number that will make the resultant size a multiple of original size

In [90]:
m.reshape(4,-4676)

array([[0.11765187, 0.74640037, 0.56633394],
       [0.55493823, 0.12560793, 0.06964189],
       [0.04378926, 0.03475215, 0.15789712],
       [0.57764405, 0.14047119, 0.05184872]])

In [91]:
m

array([[0.11765187, 0.74640037, 0.56633394, 0.55493823],
       [0.12560793, 0.06964189, 0.04378926, 0.03475215],
       [0.15789712, 0.57764405, 0.14047119, 0.05184872]])

In [92]:
m[1][1]   #indexing

0.06964189211376748

In [93]:
m[2][3]

0.05184872229586801

In [94]:
#slicing
m[0:3]   #from 0th  row to 2nd row


array([[0.11765187, 0.74640037, 0.56633394, 0.55493823],
       [0.12560793, 0.06964189, 0.04378926, 0.03475215],
       [0.15789712, 0.57764405, 0.14047119, 0.05184872]])

In [95]:
m[0:3] [2]

array([0.15789712, 0.57764405, 0.14047119, 0.05184872])

In [96]:
m[1:3,2]   #1-2 rows and then 2nd column

array([0.04378926, 0.14047119])

In [97]:
l=np.random.randint(1,100,(5,5))

In [98]:
l>50   #checks condition 

array([[ True, False, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False,  True, False,  True],
       [ True, False,  True, False, False]])

In [99]:
l[l>50]   #will return all values that satisfy the condition

array([71, 88, 61, 85, 75, 69, 63, 53, 70, 74, 67, 94, 82])

In [100]:
l

array([[71, 24, 44, 88, 61],
       [85, 75, 17, 69, 37],
       [63, 53, 19, 32, 46],
       [70, 39, 74, 17, 67],
       [94, 45, 82,  2, 25]])

In [101]:
l[2:4,1:3]

array([[53, 19],
       [39, 74]])

In [102]:
l[0][0] 

71

In [103]:
l[0][0] =2    #manipulating value ...that is reassignment

In [104]:
l[0][0] 

2

In [105]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [106]:
arr1

array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [107]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [108]:
arr1+arr2  # addition

array([[3, 3, 3],
       [3, 3, 3],
       [3, 4, 2]])

In [109]:
arr1-arr2

array([[ 1, -1, -1],
       [-1,  1, -1],
       [ 1,  0,  0]])

In [110]:
arr1*arr2   

array([[2, 2, 2],
       [2, 2, 2],
       [2, 4, 1]])

In [111]:
arr1/arr2

array([[2. , 0.5, 0.5],
       [0.5, 2. , 0.5],
       [2. , 1. , 1. ]])

In [112]:
arr1//arr2

array([[2, 0, 0],
       [0, 2, 0],
       [2, 1, 1]])

In [113]:
arr1%arr2

array([[0, 1, 1],
       [1, 0, 1],
       [0, 0, 0]])

matrix multiplication(@)

In [114]:
#no of columns of first matrix should be equal to no. of rows of second matrix 
#in resultant matrix, no of rows will be equal to no. of row of first matrix and no. of columns will be equal to no. of columns of second matrix.

In [115]:
arr1@arr2

array([[5, 7, 7],
       [6, 6, 7],
       [7, 8, 9]])

In [116]:
arr1/0

C:\Users\shanza\AppData\Local\Temp\ipykernel_648\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [117]:
arr1 + 100   #will add 100 to each value

array([[102, 101, 101],
       [101, 102, 101],
       [102, 102, 101]])

In [118]:
arr1**2

array([[4, 1, 1],
       [1, 4, 1],
       [4, 4, 1]])

broadcasting - taking value and broadcasting over whole dataset

In [119]:
arr3=np.zeros((4,4))

In [120]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
row=np.array([1,2,3,4])

In [122]:
row

array([1, 2, 3, 4])

In [123]:
arr3+row   #row wise broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [124]:
col=np.array([[1,2,3,4]])

In [125]:
col=col.T   #transpose converts rows into columns...but it has to be more than 1-dimensional

In [126]:
col

array([[1],
       [2],
       [3],
       [4]])

In [127]:
arr3+col   #column wise broadcasting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [128]:
n1=np.random.randint(1,4,(3,4))

In [129]:
np.sqrt(n1)   #square root

array([[1.        , 1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.73205081, 1.41421356, 1.        ]])

In [130]:
np.exp(n1)

array([[ 2.71828183,  2.71828183,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 7.3890561 , 20.08553692,  7.3890561 ,  2.71828183]])

In [131]:
np.log10(n1)

array([[0.        , 0.        , 0.30103   , 0.47712125],
       [0.30103   , 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.47712125, 0.30103   , 0.        ]])

numpy is used to perform mathematical functions on arrays and matrices