In [115]:
import numpy as np

In [116]:
l=[1,2,3,4]

Creating array

In [117]:
a=np.array(l)  #to convert into array

In [118]:
a

array([1, 2, 3, 4])

In [119]:
ar=np.asarray(l)

In [120]:
ar

array([1, 2, 3, 4])

In [121]:
arr=np.asanyarray(l)

In [122]:
arr

array([1, 2, 3, 4])

In [123]:
type(a)    #ndarray=n-dimensional array

numpy.ndarray

numpy can store multi-dimensional data

In [124]:
np.array([[1,2],[3,4]])  #two-dimensional

array([[1, 2],
       [3, 4]])

Creating matrix

In [125]:
b=np.matrix(l)  #matrix is by default 2-dimensional

in matrix, row is represented on x-axis,whereas column is reprented on y-axis

In [126]:
b   #matrix is subset of array

matrix([[1, 2, 3, 4]])

Converting matrix to array

In [127]:
np.asanyarray(b)   #asanyarray does not convert matrix into array

matrix([[1, 2, 3, 4]])

In [128]:
np.asarray(b)   #asarray converts matrix into array

array([[1, 2, 3, 4]])

In [129]:
np.array(b)  #array also converts matrix into array

array([[1, 2, 3, 4]])

Assigning the value of an array to another variable

In [130]:
a=np.array(l)

In [131]:
c=a

In [132]:
c

array([1, 2, 3, 4])

In [133]:
a

array([1, 2, 3, 4])

In [134]:
c[0]

1

In [135]:
c[0]=100   #changing value of 'c' at index zero.

In [136]:
c

array([100,   2,   3,   4])

In [137]:
a

array([100,   2,   3,   4])

we have changed the value at zero index in array 'c', but the value of array 'a' is also changed because when we assigned c=a,at that time new object was not created ....instead the same 'a' values were pointed towards 'c'.Memory location was not changed.This concept is called swallow copy.

Copying an array

In [138]:
d=np.copy(a)   #creating copy of array 

In [139]:
d

array([100,   2,   3,   4])

In [140]:
a

array([100,   2,   3,   4])

In [141]:
a[1]=455

In [142]:
a

array([100, 455,   3,   4])

In [143]:
d

array([100,   2,   3,   4])

when we create a copy of an array using copy() function....a new copy of array is created at a different location....hence...any changes made at 'a' is not impacted at 'd'. This is called deep copy.

Various functions to generate different types and dimensions of array

In [144]:
np.fromfunction(lambda i,j:i==j,(3,3))  #helps in generating arrays

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

here,3*3 matrix is created...then codition is checked ...i is row index and j is column index.If i==j,then it returns true else false. ( 0th row and 0th column so true,0th row and 1st column so false...and so on.)

In [145]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

here,3*3 matrix is created ,then,row index and column index are multiplied

In [146]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [147]:
iterable=(i*i for i in range(5))

In [148]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [149]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [150]:
np.fromstring('234,678 ,234',sep=' ,')

array([234., 678., 234.])

In [151]:
l1=[2,3,4,5,6]

In [152]:
ar1=np.array(l1)

In [153]:
ar1

array([2, 3, 4, 5, 6])

In [154]:
#to know dimension of array ,ndim is used
ar1.ndim

1

In [155]:
l2=[[12,56,45],[67,36,33]]
ar2=np.array(l2)

In [156]:
ar2

array([[12, 56, 45],
       [67, 36, 33]])

In [157]:
ar2.ndim

2

In [158]:
#to know size of array..that is no. of elements in array
ar2.size

6

In [159]:
ar1.size

5

In [160]:
#to know shape of array...that is ...no. of rows and columns
ar1.shape

(5,)

In [161]:
ar2

array([[12, 56, 45],
       [67, 36, 33]])

In [162]:
ar2.shape   #2 rows and 3 columns are there

(2, 3)

In [163]:
ar1.dtype   #tells datatype of array

dtype('int32')

In [164]:
ar2.dtype

dtype('int32')

In [165]:
new_ar=np.array([(1.4,45,45),(23,25,66)])

In [166]:
new_ar

array([[ 1.4, 45. , 45. ],
       [23. , 25. , 66. ]])

In [167]:
new_ar.dtype

dtype('float64')

In [168]:
range(2,8)  #range function always takes integer

range(2, 8)

In [169]:
list(range(2,8))

[2, 3, 4, 5, 6, 7]

to take floating point as starting and end points,we have arange in numpy.It can generate a range of numbers that can either be integer or float

In [170]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [171]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [172]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [173]:
np.linspace(1,5,10)   #it divides numbers between 1 and 5(or any given number ) into 10 or other specified divisions

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [174]:
np.zeros(5)  #will generate zeroes (single dimension)

array([0., 0., 0., 0., 0.])

In [175]:
np.zeros((5,6))  #5 rows six column (2 dimensional)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [176]:
np.zeros((4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [177]:
z=np.zeros((4,4,2)) #4 rows 2 columns are there and total no. of arrays are 4

In [178]:
z.ndim

3

in multi-dimensional,one array is reprented behind another array...in graph....maximum 3 dimensional can be reprented as graph or visualized.

In [179]:
np.ones((4,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [180]:
np.ones(2)

array([1., 1.])

In [181]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [182]:
o=np.ones((3,3))

In [183]:
o.ndim

2

In [184]:
o+2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [185]:
o*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [186]:
m=o+2

In [187]:
m*6

array([[18., 18., 18.],
       [18., 18., 18.],
       [18., 18., 18.]])

create an empty array

In [188]:
np.empty((3,6))


array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [189]:
#identity matrix   that is.....no. of rows is equal to no. of columns
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [190]:
np.linspace(2,4,21)   

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ])

In [191]:
np.logspace(2,5,9) #same as linespace except it gives log of that number

array([   100.        ,    237.13737057,    562.34132519,   1333.52143216,
         3162.27766017,   7498.94209332,  17782.79410039,  42169.65034286,
       100000.        ])

In [192]:
np.logspace(2,5,9, base=2)   #by default base is 10

array([ 4.        ,  5.18735822,  6.72717132,  8.72406186, 11.3137085 ,
       14.67206469, 19.02731384, 24.67537321, 32.        ])

In [193]:
np.random.randn(3,4)   #produces random array of specified size

array([[-0.71694676,  0.48226532,  0.09257142,  0.4213637 ],
       [-0.55892818, -1.24625486, -2.25142863, -0.25984077],
       [ 0.88482126,  2.0673457 , -1.27098112,  0.62225125]])

In [194]:
import pandas as pd

In [195]:
d=np.random.randn(3,4)   #will always generate data whose mean is zero and standard deviation is 1

In [196]:
pd.DataFrame(d)   #create dataframe

0         1         2         3
0  0.484170  0.509380  0.549554  0.339073
1 -0.127225  1.119012 -0.293130 -0.770617
2 -0.324727 -0.412114 -0.683202  1.381499

In [197]:
np.random.rand(3,5)  #generates any data

array([[0.8765508 , 0.78451853, 0.59027511, 0.43491183, 0.84118591],
       [0.52933333, 0.31730397, 0.6176851 , 0.05485193, 0.2430462 ],
       [0.22554002, 0.88705831, 0.26666717, 0.223198  , 0.81449925]])

In [198]:
np.random.randint(1,99,(3,4))  #will generate integer within specified range or limit

array([[25, 41, 60, 56],
       [41, 45, 67, 75],
       [93, 36, 73, 91]])

In [199]:
d1=np.random.randint(1,111,(8,9)) 

In [201]:
pd.DataFrame(d1)

0    1    2   3   4   5    6    7   8
0  48   79  103  47  31  75   53   48  92
1  60  105    2  58  92   4   73   34  19
2  82  104    1   7  34  49    6   96   3
3  58   91   96  64  96  98  104  105  30
4  76    3   74  81  53  14   98   50  85
5  99   40   23  40  33  89   32   90  75
6  40   67   65  60  51  73   83  104  53
7  51   48   93  83  12  87   72   27  28

In [204]:
m=np.random.rand(3,4) 

In [206]:
m.reshape(6,2)   #it will reshape the same data of into specified size

array([[0.03837578, 0.78866784],
       [0.03985567, 0.91959998],
       [0.89901555, 0.59732405],
       [0.60854016, 0.82377352],
       [0.66190498, 0.65685418],
       [0.56700243, 0.35061078]])

In [208]:
m.reshape(1,12)

array([[0.03837578, 0.78866784, 0.03985567, 0.91959998, 0.89901555,
        0.59732405, 0.60854016, 0.82377352, 0.66190498, 0.65685418,
        0.56700243, 0.35061078]])

in reshape,the new size has to be multiple of orginal size   ... that is if orginal size is 4*3.....then new size will be such that its product is also 12.....this means it can be 6*2,3*4,2*6,1*12 etc. Even if we don't specify column or give any negative number as column....it will still take a number that will make the resultant size a multiple of original size

In [210]:
m.reshape(4,-4676)

array([[0.03837578, 0.78866784, 0.03985567],
       [0.91959998, 0.89901555, 0.59732405],
       [0.60854016, 0.82377352, 0.66190498],
       [0.65685418, 0.56700243, 0.35061078]])

In [212]:
m

array([[0.03837578, 0.78866784, 0.03985567, 0.91959998],
       [0.89901555, 0.59732405, 0.60854016, 0.82377352],
       [0.66190498, 0.65685418, 0.56700243, 0.35061078]])

In [213]:
m[1][1]   #indexing

0.5973240481428668

In [218]:
m[2][3]

0.35061078321989314

In [221]:
#slicing
m[0:3]   #from 0th  row to 2nd row


array([[0.03837578, 0.78866784, 0.03985567, 0.91959998],
       [0.89901555, 0.59732405, 0.60854016, 0.82377352],
       [0.66190498, 0.65685418, 0.56700243, 0.35061078]])

In [222]:
m[0:3] [2]

array([0.66190498, 0.65685418, 0.56700243, 0.35061078])

In [226]:
m[1:3,2]   #1-2 rows and then 2nd column

array([0.60854016, 0.56700243])

In [229]:
l=np.random.randint(1,100,(5,5))

In [231]:
l>50   #checks condition 

array([[ True, False, False,  True, False],
       [ True,  True,  True,  True, False],
       [False,  True, False, False,  True],
       [False, False, False, False,  True],
       [ True, False,  True, False,  True]])

In [233]:
l[l>50]   #will return all values that satisfy the condition

array([71, 54, 73, 86, 74, 80, 98, 79, 86, 98, 79, 90])

In [234]:
l

array([[71,  5,  3, 54, 44],
       [73, 86, 74, 80, 28],
       [ 4, 98, 50, 32, 79],
       [ 3, 16,  1, 33, 86],
       [98, 48, 79, 44, 90]])

In [235]:
l[2:4,1:3]

array([[98, 50],
       [16,  1]])

In [237]:
l[0][0] 

71

In [240]:
l[0][0] =2    #manipulating value ...that is reassignment

In [239]:
l[0][0] 

2

In [242]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [243]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [244]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [1, 2, 2]])

In [246]:
arr1+arr2  # addition

array([[4, 3, 4],
       [2, 3, 3],
       [3, 3, 3]])

In [247]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0, -1, -1],
       [ 1, -1, -1]])

In [248]:
arr1*arr2   

array([[4, 2, 4],
       [1, 2, 2],
       [2, 2, 2]])

In [249]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 0.5, 0.5],
       [2. , 0.5, 0.5]])

In [250]:
arr1//arr2

array([[1, 0, 1],
       [1, 0, 0],
       [2, 0, 0]])

In [251]:
arr1%arr2

array([[0, 1, 0],
       [0, 1, 1],
       [0, 1, 1]])

matrix multiplication(@)

In [253]:
#no of columns of first matrix should be equal to no. of rows of second matrix 
#in resultant matrix, no of rows will be equal to no. of row of first matrix and no. of columns will be equal to no. of columns of second matrix.

In [254]:
arr1@arr2

array([[ 7, 10, 10],
       [ 4,  6,  6],
       [ 6,  8,  8]])

In [255]:
arr1/0

C:\Users\shanza\AppData\Local\Temp\ipykernel_1256\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [257]:
arr1 + 100   #will add 100 to each value

array([[102, 101, 102],
       [101, 101, 101],
       [102, 101, 101]])

In [258]:
arr1**2

array([[4, 1, 4],
       [1, 1, 1],
       [4, 1, 1]])

broadcasting - taking value and broadcasting over whole dataset

In [261]:
arr3=np.zeros((4,4))

In [266]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [263]:
row=np.array([1,2,3,4])

In [264]:
row

array([1, 2, 3, 4])

In [267]:
arr3+row   #row wise broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [270]:
col=np.array([[1,2,3,4]])

In [275]:
col=col.T   #transpose converts rows into columns...but it has to be more than 1-dimensional

In [274]:
col

array([[1],
       [2],
       [3],
       [4]])

In [276]:
arr3+col   #column wise broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [278]:
n1=np.random.randint(1,4,(3,4))

In [279]:
np.sqrt(n1)   #square root

array([[1.        , 1.73205081, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.73205081, 1.41421356],
       [1.        , 1.        , 1.        , 1.73205081]])

In [280]:
np.exp(n1)

array([[ 2.71828183, 20.08553692,  7.3890561 ,  7.3890561 ],
       [ 2.71828183,  7.3890561 , 20.08553692,  7.3890561 ],
       [ 2.71828183,  2.71828183,  2.71828183, 20.08553692]])

In [281]:
np.log10(n1)

array([[0.        , 0.47712125, 0.30103   , 0.30103   ],
       [0.        , 0.30103   , 0.47712125, 0.30103   ],
       [0.        , 0.        , 0.        , 0.47712125]])

numpy is used to perform mathematical functions on arrays and matrices