In [137]:
import numpy as np

In [138]:
l=[1,2,3,4]

Creating array

In [139]:
a=np.array(l)  #to convert into array

In [140]:
a

array([1, 2, 3, 4])

In [141]:
ar=np.asarray(l)

In [142]:
ar

array([1, 2, 3, 4])

In [143]:
arr=np.asanyarray(l)

In [144]:
arr

array([1, 2, 3, 4])

In [145]:
type(a)    #ndarray=n-dimensional array

numpy.ndarray

numpy can store multi-dimensional data

In [283]:
s=np.array([[1,2],[3,4]])  #two-dimensional

Creating matrix

In [147]:
b=np.matrix(l)  #matrix is by default 2-dimensional

in matrix, row is represented on x-axis,whereas column is reprented on y-axis

In [148]:
b   #matrix is subset of array

matrix([[1, 2, 3, 4]])

Converting matrix to array

In [149]:
np.asanyarray(b)   #asanyarray does not convert matrix into array

matrix([[1, 2, 3, 4]])

In [150]:
np.asarray(b)   #asarray converts matrix into array

array([[1, 2, 3, 4]])

In [151]:
np.array(b)  #array also converts matrix into array

array([[1, 2, 3, 4]])

Assigning the value of an array to another variable

In [152]:
a=np.array(l)

In [153]:
c=a

In [154]:
c

array([1, 2, 3, 4])

In [155]:
a

array([1, 2, 3, 4])

In [156]:
c[0]

1

In [157]:
c[0]=100   #changing value of 'c' at index zero.

In [158]:
c

array([100,   2,   3,   4])

In [159]:
a

array([100,   2,   3,   4])

we have changed the value at zero index in array 'c', but the value of array 'a' is also changed because when we assigned c=a,at that time new object was not created ....instead the same 'a' values were pointed towards 'c'.Memory location was not changed.This concept is called swallow copy.

Copying an array

In [160]:
d=np.copy(a)   #creating copy of array 

In [161]:
d

array([100,   2,   3,   4])

In [162]:
a

array([100,   2,   3,   4])

In [163]:
a[1]=455

In [164]:
a

array([100, 455,   3,   4])

In [165]:
d

array([100,   2,   3,   4])

when we create a copy of an array using copy() function....a new copy of array is created at a different location....hence...any changes made at 'a' is not impacted at 'd'. This is called deep copy.

Various functions to generate different types and dimensions of array

In [166]:
np.fromfunction(lambda i,j:i==j,(3,3))  #helps in generating arrays

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

here,3*3 matrix is created...then codition is checked ...i is row index and j is column index.If i==j,then it returns true else false. ( 0th row and 0th column so true,0th row and 1st column so false...and so on.)

In [167]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

here,3*3 matrix is created ,then,row index and column index are multiplied

In [168]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [169]:
iterable=(i*i for i in range(5))

In [170]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [171]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [172]:
np.fromstring('234,678 ,234',sep=' ,')

array([234., 678., 234.])

In [173]:
l1=[2,3,4,5,6]

In [174]:
ar1=np.array(l1)

In [175]:
ar1

array([2, 3, 4, 5, 6])

In [176]:
#to know dimension of array ,ndim is used
ar1.ndim

1

In [177]:
l2=[[12,56,45],[67,36,33]]
ar2=np.array(l2)

In [178]:
ar2

array([[12, 56, 45],
       [67, 36, 33]])

In [179]:
ar2.ndim

2

In [180]:
#to know size of array..that is no. of elements in array
ar2.size

6

In [181]:
ar1.size

5

In [182]:
#to know shape of array...that is ...no. of rows and columns
ar1.shape

(5,)

In [183]:
ar2

array([[12, 56, 45],
       [67, 36, 33]])

In [184]:
ar2.shape   #2 rows and 3 columns are there

(2, 3)

In [185]:
ar1.dtype   #tells datatype of array

dtype('int32')

In [186]:
ar2.dtype

dtype('int32')

In [187]:
new_ar=np.array([(1.4,45,45),(23,25,66)])

In [188]:
new_ar

array([[ 1.4, 45. , 45. ],
       [23. , 25. , 66. ]])

In [189]:
new_ar.dtype

dtype('float64')

In [190]:
range(2,8)  #range function always takes integer

range(2, 8)

In [191]:
list(range(2,8))

[2, 3, 4, 5, 6, 7]

to take floating point as starting and end points,we have arange in numpy.It can generate a range of numbers that can either be integer or float

In [192]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [193]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [194]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [195]:
np.linspace(1,5,10)   #it divides numbers between 1 and 5(or any given number ) into 10 or other specified divisions

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [196]:
np.zeros(5)  #will generate zeroes (single dimension)

array([0., 0., 0., 0., 0.])

In [197]:
np.zeros((5,6))  #5 rows six column (2 dimensional)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [198]:
np.zeros((4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [199]:
z=np.zeros((4,4,2)) #4 rows 2 columns are there and total no. of arrays are 4

In [200]:
z.ndim

3

in multi-dimensional,one array is reprented behind another array...in graph....maximum 3 dimensional can be reprented as graph or visualized.

In [201]:
np.ones((4,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [202]:
np.ones(2)

array([1., 1.])

In [203]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [204]:
o=np.ones((3,3))

In [205]:
o.ndim

2

In [206]:
o+2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [207]:
o*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [208]:
m=o+2

In [209]:
m*6

array([[18., 18., 18.],
       [18., 18., 18.],
       [18., 18., 18.]])

create an empty array

In [210]:
np.empty((3,6))


array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [211]:
#identity matrix   that is.....no. of rows is equal to no. of columns
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [212]:
np.linspace(2,4,21)   

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ])

In [213]:
np.logspace(2,5,9) #same as linespace except it gives log of that number

array([   100.        ,    237.13737057,    562.34132519,   1333.52143216,
         3162.27766017,   7498.94209332,  17782.79410039,  42169.65034286,
       100000.        ])

In [214]:
np.logspace(2,5,9, base=2)   #by default base is 10

array([ 4.        ,  5.18735822,  6.72717132,  8.72406186, 11.3137085 ,
       14.67206469, 19.02731384, 24.67537321, 32.        ])

In [215]:
np.random.randn(3,4)   #produces random array of specified size

array([[-0.74753586, -0.0593843 ,  0.70923632, -0.17695546],
       [ 0.13286853,  0.3235475 ,  2.63504656,  0.79704066],
       [-0.34104136, -2.25503274, -0.78134149, -0.48605207]])

In [216]:
import pandas as pd

In [217]:
d=np.random.randn(3,4)   #will always generate data whose mean is zero and standard deviation is 1

In [218]:
pd.DataFrame(d)   #create dataframe

0         1         2         3
0  0.495256 -0.765252 -0.407546  1.597916
1 -0.154689  0.353206  0.452582  0.388705
2  0.985376  0.853419  0.903916 -0.285791

In [219]:
np.random.rand(3,5)  #generates any data

array([[0.2444156 , 0.63946187, 0.86839324, 0.74791547, 0.02216623],
       [0.0095276 , 0.01537928, 0.91361484, 0.57135972, 0.01840462],
       [0.05497404, 0.72832366, 0.4719323 , 0.7213901 , 0.11601365]])

In [220]:
np.random.randint(1,99,(3,4))  #will generate integer within specified range or limit

array([[21, 37, 27,  6],
       [36, 85, 21, 91],
       [ 4, 23, 41, 38]])

In [221]:
d1=np.random.randint(1,111,(8,9)) 

In [222]:
pd.DataFrame(d1)

0    1    2   3   4    5   6   7   8
0  80   21    1  51  33   25  95  92   4
1  31  104   41  45  23    6  91  40  13
2  32  105   50  33  75  104  58  68  35
3  27   73   67  60  41    7  82  59  36
4   6   46   61  80   7   18  41   9  92
5  71   87  108  75  82   35  13  72  95
6  38   88   19  15  95   82  76  10  57
7  93   85   62   3  39   47  60  24   9

In [223]:
m=np.random.rand(3,4) 

In [224]:
m.reshape(6,2)   #it will reshape the same data of into specified size

array([[0.80795925, 0.86155858],
       [0.88046029, 0.42169085],
       [0.16690999, 0.71685098],
       [0.41373507, 0.98424745],
       [0.69712027, 0.6339756 ],
       [0.36600922, 0.63120977]])

In [225]:
m.reshape(1,12)

array([[0.80795925, 0.86155858, 0.88046029, 0.42169085, 0.16690999,
        0.71685098, 0.41373507, 0.98424745, 0.69712027, 0.6339756 ,
        0.36600922, 0.63120977]])

in reshape,the new size has to be multiple of orginal size   ... that is if orginal size is 4*3.....then new size will be such that its product is also 12.....this means it can be 6*2,3*4,2*6,1*12 etc. Even if we don't specify column or give any negative number as column....it will still take a number that will make the resultant size a multiple of original size

In [226]:
m.reshape(4,-4676)

array([[0.80795925, 0.86155858, 0.88046029],
       [0.42169085, 0.16690999, 0.71685098],
       [0.41373507, 0.98424745, 0.69712027],
       [0.6339756 , 0.36600922, 0.63120977]])

In [227]:
m

array([[0.80795925, 0.86155858, 0.88046029, 0.42169085],
       [0.16690999, 0.71685098, 0.41373507, 0.98424745],
       [0.69712027, 0.6339756 , 0.36600922, 0.63120977]])

In [228]:
m[1][1]   #indexing

0.7168509757811703

In [229]:
m[2][3]

0.6312097655278889

In [230]:
#slicing
m[0:3]   #from 0th  row to 2nd row


array([[0.80795925, 0.86155858, 0.88046029, 0.42169085],
       [0.16690999, 0.71685098, 0.41373507, 0.98424745],
       [0.69712027, 0.6339756 , 0.36600922, 0.63120977]])

In [231]:
m[0:3] [2]

array([0.69712027, 0.6339756 , 0.36600922, 0.63120977])

In [232]:
m[1:3,2]   #1-2 rows and then 2nd column

array([0.41373507, 0.36600922])

In [233]:
l=np.random.randint(1,100,(5,5))

In [234]:
l>50   #checks condition 

array([[False,  True, False,  True, False],
       [ True,  True,  True,  True, False],
       [False,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [235]:
l[l>50]   #will return all values that satisfy the condition

array([58, 55, 66, 82, 88, 56, 98, 96, 71, 69, 68, 63, 67, 66, 94, 65, 72])

In [236]:
l

array([[41, 58, 19, 55,  9],
       [66, 82, 88, 56, 34],
       [14, 98, 46, 96, 28],
       [71, 69, 68, 63, 67],
       [66, 94, 65, 72,  6]])

In [237]:
l[2:4,1:3]

array([[98, 46],
       [69, 68]])

In [238]:
l[0][0] 

41

In [239]:
l[0][0] =2    #manipulating value ...that is reassignment

In [240]:
l[0][0] 

2

In [241]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [242]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [243]:
arr2

array([[1, 1, 1],
       [2, 2, 1],
       [2, 2, 2]])

In [244]:
arr1+arr2  # addition

array([[3, 3, 3],
       [4, 3, 2],
       [4, 4, 3]])

In [245]:
arr1-arr2

array([[ 1,  1,  1],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [246]:
arr1*arr2   

array([[2, 2, 2],
       [4, 2, 1],
       [4, 4, 2]])

In [247]:
arr1/arr2

array([[2. , 2. , 2. ],
       [1. , 0.5, 1. ],
       [1. , 1. , 0.5]])

In [248]:
arr1//arr2

array([[2, 2, 2],
       [1, 0, 1],
       [1, 1, 0]])

In [249]:
arr1%arr2

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

matrix multiplication(@)

In [250]:
#no of columns of first matrix should be equal to no. of rows of second matrix 
#in resultant matrix, no of rows will be equal to no. of row of first matrix and no. of columns will be equal to no. of columns of second matrix.

In [251]:
arr1@arr2

array([[10, 10,  8],
       [ 6,  6,  5],
       [ 8,  8,  6]])

In [252]:
arr1/0

C:\Users\shanza\AppData\Local\Temp\ipykernel_6108\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [253]:
arr1 + 100   #will add 100 to each value

array([[102, 102, 102],
       [102, 101, 101],
       [102, 102, 101]])

In [254]:
arr1**2

array([[4, 4, 4],
       [4, 1, 1],
       [4, 4, 1]])

broadcasting - taking value and broadcasting over whole dataset

In [255]:
arr3=np.zeros((4,4))

In [256]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [257]:
row=np.array([1,2,3,4])

In [258]:
row

array([1, 2, 3, 4])

In [259]:
arr3+row   #row wise broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [260]:
col=np.array([[1,2,3,4]])

In [261]:
col=col.T   #transpose converts rows into columns...but it has to be more than 1-dimensional

In [262]:
col

array([[1],
       [2],
       [3],
       [4]])

In [263]:
arr3+col   #column wise broadcasting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [264]:
n1=np.random.randint(1,4,(3,4))

In [265]:
np.sqrt(n1)   #square root

array([[1.        , 1.73205081, 1.41421356, 1.73205081],
       [1.73205081, 1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 1.        ]])

In [266]:
np.exp(n1)

array([[ 2.71828183, 20.08553692,  7.3890561 , 20.08553692],
       [20.08553692,  2.71828183,  7.3890561 , 20.08553692],
       [20.08553692, 20.08553692, 20.08553692,  2.71828183]])

In [267]:
np.log10(n1)

array([[0.        , 0.47712125, 0.30103   , 0.47712125],
       [0.47712125, 0.        , 0.30103   , 0.47712125],
       [0.47712125, 0.47712125, 0.47712125, 0.        ]])

numpy is used to perform mathematical functions on arrays and matrices