MANIPULATION

In [3]:
import numpy as np

In [4]:
arr=np.random.randint(1,10,(3,4))

In [5]:
arr

array([[4, 1, 1, 6],
       [9, 2, 7, 8],
       [3, 2, 1, 7]])

In [6]:
arr.reshape(6,2)

array([[4, 1],
       [1, 6],
       [9, 2],
       [7, 8],
       [3, 2],
       [1, 7]])

In [7]:
arr.reshape(2,6)

array([[4, 1, 1, 6, 9, 2],
       [7, 8, 3, 2, 1, 7]])

In [8]:
arr.T

array([[4, 9, 3],
       [1, 2, 2],
       [1, 7, 1],
       [6, 8, 7]])

In [9]:
arr.flatten()   #converts the array into one-dimension

array([4, 1, 1, 6, 9, 2, 7, 8, 3, 2, 1, 7])

In [10]:
arr1=np.array([1,2,3,3,4])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)   #changes dimension from 1 to 2

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [13]:
np.expand_dims(arr1,axis=0) 

array([[1, 2, 3, 3, 4]])

In [14]:
arr

array([[4, 1, 1, 6],
       [9, 2, 7, 8],
       [3, 2, 1, 7]])

In [15]:
np.squeeze(arr)

array([[4, 1, 1, 6],
       [9, 2, 7, 8],
       [3, 2, 1, 7]])

squeeze converts multidimensional array into single dimension when single element is present

In [16]:
data=np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 3, 4])

In [20]:
np.repeat(arr1,3)   #each element will be repeated as many times as it is specified

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [21]:
arr1

array([1, 2, 3, 3, 4])

In [22]:
np.roll(arr1,2)   #shifts each element

array([3, 4, 1, 2, 3])

In [23]:
np.roll(arr1,4)

array([2, 3, 3, 4, 1])

In [24]:
np.diag(arr1)   #will place all 1-D data provided at diagonal....and rest positions will be zero

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

BINARY OPERATIONS

In [25]:
arr3=np.random.randint(1,10,(3,4))

In [26]:
arr4=np.random.randint(1,10,(3,4))

In [27]:
arr3

array([[1, 6, 7, 1],
       [5, 6, 9, 6],
       [1, 2, 6, 7]])

In [28]:
arr4

array([[6, 2, 9, 6],
       [5, 5, 2, 2],
       [3, 9, 7, 9]])

In [30]:
arr3+arr4

array([[ 7,  8, 16,  7],
       [10, 11, 11,  8],
       [ 4, 11, 13, 16]])

In [31]:
arr3*arr4

array([[ 6, 12, 63,  6],
       [25, 30, 18, 12],
       [ 3, 18, 42, 63]])

In [32]:
arr3-arr4

array([[-5,  4, -2, -5],
       [ 0,  1,  7,  4],
       [-2, -7, -1, -2]])

In [33]:
arr3%arr4

array([[1, 0, 7, 1],
       [0, 1, 1, 0],
       [1, 2, 6, 7]])

In [34]:
arr3**arr4

array([[       1,       36, 40353607,        1],
       [    3125,     7776,       81,       36],
       [       1,      512,   279936, 40353607]])

In [36]:
arr3

array([[1, 6, 7, 1],
       [5, 6, 9, 6],
       [1, 2, 6, 7]])

In [37]:
arr4

array([[6, 2, 9, 6],
       [5, 5, 2, 2],
       [3, 9, 7, 9]])

In [35]:
arr3 & arr4

array([[0, 2, 1, 0],
       [5, 4, 0, 2],
       [1, 0, 6, 1]])

In [38]:
~arr3  #negation

array([[ -2,  -7,  -8,  -2],
       [ -6,  -7, -10,  -7],
       [ -2,  -3,  -7,  -8]])

In [39]:
arr3 | arr4

array([[ 7,  6, 15,  7],
       [ 5,  7, 11,  6],
       [ 3, 11,  7, 15]])

In [40]:
arr3>arr4

array([[False,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False, False]])

STRING FUNCTIONS

In [42]:
s=np.array(['shanza','sayeed'])

In [43]:
s

array(['shanza', 'sayeed'], dtype='<U6')

In [46]:
np.char.upper(s) #converts string to upper case

array(['SHANZA', 'SAYEED'], dtype='<U6')

In [47]:
np.char.title(s)  #titlecase

array(['Shanza', 'Sayeed'], dtype='<U6')

In [48]:
np.char.capitalize(s)

array(['Shanza', 'Sayeed'], dtype='<U6')

MATHEMATICAL FUNCTIONS

In [49]:
arr3

array([[1, 6, 7, 1],
       [5, 6, 9, 6],
       [1, 2, 6, 7]])

In [51]:
np.sin(arr3)

array([[ 0.84147098, -0.2794155 ,  0.6569866 ,  0.84147098],
       [-0.95892427, -0.2794155 ,  0.41211849, -0.2794155 ],
       [ 0.84147098,  0.90929743, -0.2794155 ,  0.6569866 ]])

In [52]:
np.cos(arr3)

array([[ 0.54030231,  0.96017029,  0.75390225,  0.54030231],
       [ 0.28366219,  0.96017029, -0.91113026,  0.96017029],
       [ 0.54030231, -0.41614684,  0.96017029,  0.75390225]])

In [53]:
np.tan(arr3)

array([[ 1.55740772, -0.29100619,  0.87144798,  1.55740772],
       [-3.38051501, -0.29100619, -0.45231566, -0.29100619],
       [ 1.55740772, -2.18503986, -0.29100619,  0.87144798]])

In [54]:
np.tanh(arr3)  #hypertangent

array([[0.76159416, 0.99998771, 0.99999834, 0.76159416],
       [0.9999092 , 0.99998771, 0.99999997, 0.99998771],
       [0.76159416, 0.96402758, 0.99998771, 0.99999834]])

In [55]:
np.log10(arr3)

array([[0.        , 0.77815125, 0.84509804, 0.        ],
       [0.69897   , 0.77815125, 0.95424251, 0.77815125],
       [0.        , 0.30103   , 0.77815125, 0.84509804]])

In [56]:
np.exp(arr3)

array([[2.71828183e+00, 4.03428793e+02, 1.09663316e+03, 2.71828183e+00],
       [1.48413159e+02, 4.03428793e+02, 8.10308393e+03, 4.03428793e+02],
       [2.71828183e+00, 7.38905610e+00, 4.03428793e+02, 1.09663316e+03]])

In [57]:
np.sqrt(arr3)

array([[1.        , 2.44948974, 2.64575131, 1.        ],
       [2.23606798, 2.44948974, 3.        , 2.44948974],
       [1.        , 1.41421356, 2.44948974, 2.64575131]])

In [58]:
np.power(arr3,2)

array([[ 1, 36, 49,  1],
       [25, 36, 81, 36],
       [ 1,  4, 36, 49]], dtype=int32)

In [59]:
np.mean(arr3)

4.75

In [61]:
np.median(arr3)

6.0

In [62]:
np.std(arr3)

2.6496855159307744

In [63]:
np.var(arr3)

7.020833333333333

In [64]:
np.min(arr3)

1

In [65]:
np.max(arr3)

9