sort, search and counting functions

In [2]:
import numpy as np

In [3]:
arr=np.array([111,4,34,56,73,222,44])

In [4]:
arr

array([111,   4,  34,  56,  73, 222,  44])

In [5]:
np.sort(arr)

array([  4,  34,  44,  56,  73, 111, 222])

In [6]:
np.searchsorted(arr,35)   #it tells at what poition will the specified number go when sorted in ascending order

3

In [7]:
arr1=np.array([0,345,454,0,0,0,0,0,0,0,0])

In [8]:
np.count_nonzero(arr1)   #returns no. of non-zero elements in an array

2

In [9]:
arr

array([111,   4,  34,  56,  73, 222,  44])

In [10]:
#to find position(indexes) of element which specifies a particular condition

In [11]:
np.where(arr>35)

(array([0, 3, 4, 5, 6], dtype=int64),)

In [12]:
np.extract(arr>6 ,arr)   #returns elements that specify the given condition

array([111,  34,  56,  73, 222,  44])

In [13]:
#represent in bytes
arr.byteswap()

array([1862270976,   67108864,  570425344,  939524096, 1224736768,
       -570425344,  738197504])

In [14]:
arr

array([111,   4,  34,  56,  73, 222,  44])

In [15]:
#deep copy
a=np.copy(arr)

In [16]:
b=arr.view()   #swallow copy

In [17]:
a

array([111,   4,  34,  56,  73, 222,  44])

In [18]:
b

array([111,   4,  34,  56,  73, 222,  44])

matrix library

In [19]:
import numpy.matlib as nm

In [20]:
nm.zeros(5)   #generates matrix

matrix([[0., 0., 0., 0., 0.]])

In [21]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
nm.eye(5)  #identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

linear algebra

In [40]:
a11=np.random.randint([[2,4],[4,3]])

In [41]:
a11

array([[1, 1],
       [1, 2]])

In [32]:
a11.ndim

2

In [25]:
a12=np.random.randint([[2,3],[4,5]])

In [28]:
a12

array([[1, 1],
       [1, 3]])

In [26]:
a11@a12  #matrix multiplication

array([[1, 1],
       [4, 6]])

In [27]:
np.dot(a11,a12)  #dot product

array([[1, 1],
       [4, 6]])