MANIPULATION

In [3]:
import numpy as np

In [4]:
arr=np.random.randint(1,10,(3,4))

In [5]:
arr

array([[2, 5, 4, 5],
       [5, 6, 9, 6],
       [8, 2, 1, 6]])

In [6]:
arr.reshape(6,2)

array([[2, 5],
       [4, 5],
       [5, 6],
       [9, 6],
       [8, 2],
       [1, 6]])

In [7]:
arr.reshape(2,6)

array([[2, 5, 4, 5, 5, 6],
       [9, 6, 8, 2, 1, 6]])

In [8]:
arr.T

array([[2, 5, 8],
       [5, 6, 2],
       [4, 9, 1],
       [5, 6, 6]])

In [9]:
arr.flatten()   #converts the array into one-dimension

array([2, 5, 4, 5, 5, 6, 9, 6, 8, 2, 1, 6])

In [10]:
arr1=np.array([1,2,3,3,4])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)   #changes dimension from 1 to 2

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [13]:
np.expand_dims(arr1,axis=0) 

array([[1, 2, 3, 3, 4]])

In [14]:
arr

array([[2, 5, 4, 5],
       [5, 6, 9, 6],
       [8, 2, 1, 6]])

In [15]:
np.squeeze(arr)

array([[2, 5, 4, 5],
       [5, 6, 9, 6],
       [8, 2, 1, 6]])

squeeze converts multidimensional array into single dimension when single element is present

In [73]:
data=np.array([[1,4],[2,5],[3,6]])

In [74]:
data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
data.ndim

2

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 3, 4])

In [21]:
np.repeat(arr1,3)   #each element will be repeated as many times as it is specified

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [22]:
arr1

array([1, 2, 3, 3, 4])

In [23]:
np.roll(arr1,2)   #shifts each element

array([3, 4, 1, 2, 3])

In [24]:
np.roll(arr1,4)

array([2, 3, 3, 4, 1])

In [25]:
np.diag(arr1)   #will place all 1-D data provided at diagonal....and rest positions will be zero

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

BINARY OPERATIONS

In [26]:
arr3=np.random.randint(1,10,(3,4))

In [27]:
arr4=np.random.randint(1,10,(3,4))

In [28]:
arr3

array([[8, 6, 1, 9],
       [9, 8, 8, 3],
       [2, 6, 7, 1]])

In [29]:
arr4

array([[6, 7, 3, 7],
       [8, 4, 2, 1],
       [2, 2, 7, 2]])

In [30]:
arr3+arr4

array([[14, 13,  4, 16],
       [17, 12, 10,  4],
       [ 4,  8, 14,  3]])

In [31]:
arr3*arr4

array([[48, 42,  3, 63],
       [72, 32, 16,  3],
       [ 4, 12, 49,  2]])

In [32]:
arr3-arr4

array([[ 2, -1, -2,  2],
       [ 1,  4,  6,  2],
       [ 0,  4,  0, -1]])

In [33]:
arr3%arr4

array([[2, 6, 1, 2],
       [1, 0, 0, 0],
       [0, 0, 0, 1]])

In [34]:
arr3**arr4

array([[  262144,   279936,        1,  4782969],
       [43046721,     4096,       64,        3],
       [       4,       36,   823543,        1]])

In [35]:
arr3

array([[8, 6, 1, 9],
       [9, 8, 8, 3],
       [2, 6, 7, 1]])

In [36]:
arr4

array([[6, 7, 3, 7],
       [8, 4, 2, 1],
       [2, 2, 7, 2]])

In [37]:
arr3 & arr4

array([[0, 6, 1, 1],
       [8, 0, 0, 1],
       [2, 2, 7, 0]])

In [38]:
~arr3  #negation

array([[ -9,  -7,  -2, -10],
       [-10,  -9,  -9,  -4],
       [ -3,  -7,  -8,  -2]])

In [39]:
arr3 | arr4

array([[14,  7,  3, 15],
       [ 9, 12, 10,  3],
       [ 2,  6,  7,  3]])

In [40]:
arr3>arr4

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True, False, False]])

STRING FUNCTIONS

In [41]:
s=np.array(['shanza','sayeed'])

In [42]:
s

array(['shanza', 'sayeed'], dtype='<U6')

In [43]:
np.char.upper(s) #converts string to upper case

array(['SHANZA', 'SAYEED'], dtype='<U6')

In [44]:
np.char.title(s)  #titlecase

array(['Shanza', 'Sayeed'], dtype='<U6')

In [45]:
np.char.capitalize(s)

array(['Shanza', 'Sayeed'], dtype='<U6')

MATHEMATICAL FUNCTIONS

In [46]:
arr3

array([[8, 6, 1, 9],
       [9, 8, 8, 3],
       [2, 6, 7, 1]])

In [47]:
np.sin(arr3)

array([[ 0.98935825, -0.2794155 ,  0.84147098,  0.41211849],
       [ 0.41211849,  0.98935825,  0.98935825,  0.14112001],
       [ 0.90929743, -0.2794155 ,  0.6569866 ,  0.84147098]])

In [48]:
np.cos(arr3)

array([[-0.14550003,  0.96017029,  0.54030231, -0.91113026],
       [-0.91113026, -0.14550003, -0.14550003, -0.9899925 ],
       [-0.41614684,  0.96017029,  0.75390225,  0.54030231]])

In [49]:
np.tan(arr3)

array([[-6.79971146, -0.29100619,  1.55740772, -0.45231566],
       [-0.45231566, -6.79971146, -6.79971146, -0.14254654],
       [-2.18503986, -0.29100619,  0.87144798,  1.55740772]])

In [50]:
np.tanh(arr3)  #hypertangent

array([[0.99999977, 0.99998771, 0.76159416, 0.99999997],
       [0.99999997, 0.99999977, 0.99999977, 0.99505475],
       [0.96402758, 0.99998771, 0.99999834, 0.76159416]])

In [51]:
np.log10(arr3)

array([[0.90308999, 0.77815125, 0.        , 0.95424251],
       [0.95424251, 0.90308999, 0.90308999, 0.47712125],
       [0.30103   , 0.77815125, 0.84509804, 0.        ]])

In [52]:
np.exp(arr3)

array([[2.98095799e+03, 4.03428793e+02, 2.71828183e+00, 8.10308393e+03],
       [8.10308393e+03, 2.98095799e+03, 2.98095799e+03, 2.00855369e+01],
       [7.38905610e+00, 4.03428793e+02, 1.09663316e+03, 2.71828183e+00]])

In [53]:
np.sqrt(arr3)

array([[2.82842712, 2.44948974, 1.        , 3.        ],
       [3.        , 2.82842712, 2.82842712, 1.73205081],
       [1.41421356, 2.44948974, 2.64575131, 1.        ]])

In [54]:
np.power(arr3,2)

array([[64, 36,  1, 81],
       [81, 64, 64,  9],
       [ 4, 36, 49,  1]], dtype=int32)

In [55]:
np.mean(arr3)

5.666666666666667

In [56]:
np.median(arr3)

6.5

In [57]:
np.std(arr3)

2.9533408577782247

In [58]:
np.var(arr3)

8.722222222222221

In [59]:
np.min(arr3)

1

In [60]:
np.max(arr3)

9